# The URL the site will be built for
base_url = "https://ivan.fraixed.es"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# The site theme to use
theme = "kissi"

# When set to "true", the generated HTML files are minified.
minify_html = true

[extra.kissi]
portrait = "portrait.png"
fullname = "Ivan Fraixedes"
tagline = "Software Engineer"
links = [
    { title = "github", url = "https://github.com/ifraixedes", icon = "github" },
    { title = "linkedin", url = "https://linkedin.com/in/ifraixedes", icon = "linkedin-in" },
    { title = "my blog", url = "https://blog.fraixed.es", text = "blog" },
    { title = "cv", url = "/files/CV_Ivan_Fraixedes.pdf", text = "CV" },
    { title = "talks", url = "https://www.youtube.com/playlist?list=PLq3ZCWgABWn78SzUgQ5GGKQdUYlVvId1-", icon = "youtube"},
]
